asp-final-project-team-alpha-main/Real_Estate_Project/Controllers/CustomerOperationsController.cs
using Microsoft.AspNet.Identity;
using Real_Estate_Project.Authorization_Utilities;
using Real_Estate_Project.DataAccess.Interfaces;
using Real_Estate_Project.Models.Domain_Models;
using Real_Estate_Project.ViewModels;
using System;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Real_Estate_Project.Controllers
{
    [Authorize(Roles = RoleNames.OFFICE_MANAGER + "," + RoleNames.ADMIN + "," + RoleNames.AGENT)]
    public class CustomerOperationsController : Controller
    {
        private ICustomerRepo _customerRepo;
        private CustomerViewModel model;

        public CustomerOperationsController
            (ICustomerRepo customerRepo,
            CustomerViewModel customerVM )
        {
            _customerRepo = customerRepo;
            model = customerVM;
        }


        public async Task<ActionResult> Index()
        {
            try
            {
                var customers =await _customerRepo.GetAll();

                if (customers != null)
                    model.customerList = customers;
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }
            return View(model);
        }


        public ActionResult Create()
        {
            return View(model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Customer inputModel)
        {
            model.inputModel = inputModel;

            if (ModelState.IsValid)
            {
                try
                {
                    var currentLoggedUserId = User.Identity.GetUserId();
                    var currentLoggedUserRes = await UserIdentityManager
                                                .GetUserById(currentLoggedUserId);

                    inputModel.UserCreatorId = currentLoggedUserRes.registeredUser.ID;
                    inputModel.UserUpdatorId = currentLoggedUserRes.registeredUser.ID;
                    inputModel.DateCreated = DateTime.Now;
                    inputModel.DateUpdated = DateTime.Now;
                    inputModel.IsActive = true;

                    await _customerRepo.Create(inputModel);

                    return RedirectToAction("Index");
                }
                catch(Exception ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                    return View("Create", model);
                }
                
            }
            return View("Create", model);
        }


        public async Task<ActionResult> Details(int? id)
        {
            if (id.HasValue)
            {
                try
                {
                    var customer = await _customerRepo.Get(id.Value);

                    if (customer == null)
                        return HttpNotFound();

                    model.inputModel = customer;
                }
                catch(Exception ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                }
              
                return View(model);
            }

            return HttpNotFound();
        }


        public async Task<ActionResult> Edit(int? id)
        {
            if (id.HasValue)
            {
                try
                {
                    var customer = await _customerRepo.Get(id.Value);

                    if (customer == null)
                        return HttpNotFound();

                    model.inputModel = customer;
                }
                catch(Exception ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                }
              
                return View(model);
            }

            return HttpNotFound();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(CustomerViewModel returnModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var currentLoggedUserId = User.Identity.GetUserId();

                    var currentLoggedUserRes = await UserIdentityManager
                        .GetUserById(currentLoggedUserId);

                    if (currentLoggedUserRes != null)
                    {

                        returnModel.inputModel.UserUpdatorId = 
                            currentLoggedUserRes.registeredUser.ID;

                        returnModel.inputModel.DateUpdated = DateTime.Now;

                        await _customerRepo.Update(returnModel.inputModel);

                        model.inputModel = returnModel.inputModel;


                        return View("Details", model);
                    }
                    else
                    {
                        return HttpNotFound();
                    }

                }
                catch (Exception ex)
                {
                    model.inputModel = returnModel.inputModel;

                    ModelState.AddModelError(string.Empty, ex.Message);
                    return View("Edit", model);
                }

            }
            model.inputModel = returnModel.inputModel;

            return View("Edit", model);
        }


        public async Task<ActionResult> Delete(int? id)
        {
            if (id.HasValue)
            {
                try
                {
                    var customer = await _customerRepo.Get(id.Value);

                    if (customer == null)
                        return HttpNotFound();

                    model.inputModel = customer;
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                }

                return View(model);
            }
            return HttpNotFound();
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var customer = await _customerRepo.Get(id);

                customer.IsActive = false;
                var res = await _customerRepo.Delete(customer);

                if(res != 1)
                {
                    ModelState.AddModelError(string.Empty,
                        "couldn't Archive Customer");

                    model.inputModel = customer;

                    return View(model);
                }

            }catch(Exception ex)
            {
                ModelState.AddModelError(string.Empty,ex.Message);
                model.inputModel = await _customerRepo.Get(id);

                return View(model);
            }

            return RedirectToAction("Index");
        }


        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            if (disposing)
            {
                _customerRepo.Dispose();
            }
        }
    }
}

asp-final-project-team-alpha-main/Real_Estate_Project/Controllers/RoleFilterController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Real_Estate_Project.Authorization_Utilities;
using Real_Estate_Project.Models;
using Real_Estate_Project.Models.Domain_Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Real_Estate_Project.Controllers
{
    public class RoleFilterController : Controller
    {
        private const string USER_OEPRATIONS_PATH = "UserOperations";
        private const string CUSTOMER_OPERATIONS_PATH = "CustomerOperations";
        private const string IDENTITY_OPERATIONS_PATH = "Account";
        private const string NOT_AUTHORIZED_PATH = "RoleNotAuthorized";
        private SimpleErrorModel errorModel;

        public RoleFilterController(SimpleErrorModel erroM)
        {
            errorModel = erroM;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        // GET: RoleFilter
        public ActionResult Index()
        {
            return View();
        }


        #region User related Operations
        //Only authorized user will be redirected
        public ActionResult GetUsers()
        {
            var res = UserManager.IsInRole(User.Identity.GetUserId(), RoleNames.ADMIN)
                || UserManager.IsInRole(User.Identity.GetUserId(), RoleNames.OFFICE_MANAGER);

            if (res)
            {
                return RedirectToAction("Index", USER_OEPRATIONS_PATH);
            }
            else
            {
                errorModel.ErrorMessage = "Agent cannot access users resource";
                //send to an error page for role is not authorized
                return View(NOT_AUTHORIZED_PATH, errorModel);
            }
        }

        public ActionResult CreateUser()
        {
            var res = UserManager.IsInRole(User.Identity.GetUserId(), RoleNames.OFFICE_MANAGER);
            if (res)
            {
                return RedirectToAction("Register", IDENTITY_OPERATIONS_PATH);
            }
            else
            {
                errorModel.ErrorMessage = "Agent cannot access users resource";
                //send to an error page for role is not authorized
                return View(NOT_AUTHORIZED_PATH, errorModel);
            }
        }

        public ActionResult GetUserDetails(int ?id)
        {
            var res = UserManager.IsInRole(User.Identity.GetUserId(), RoleNames.OFFICE_MANAGER);
            if (id.HasValue)
            {
                if (res)
                {
                    return RedirectToAction("Details", USER_OEPRATIONS_PATH, new {id= id});
                }
                else
                {
                    errorModel.ErrorMessage = "Agent cannot access users resource";
                    //send to an error page for role is not authorized
                    return View(NOT_AUTHORIZED_PATH, errorModel);
                }
            }
            return HttpNotFound();
        }

        public ActionResult EditUser(int? id)
        {
            var res = UserManager.IsInRole(User.Identity.GetUserId(), RoleNames.OFFICE_MANAGER);
            if (id.HasValue)
            {
                if (res)
                {
                    return RedirectToAction("Edit", USER_OEPRATIONS_PATH, new { id = id });
                }
                else
                {
                    errorModel.ErrorMessage = "Agent cannot access users resource";
                    //send to an error page for role is not authorized
                    return View(NOT_AUTHORIZED_PATH, errorModel);
                }
            }
            return HttpNotFound();
        }
        #endregion

        #region Customer Related Operations
        public ActionResult GetCustomers()
        {
            var res = UserManager.IsInRole(User.Identity.GetUserId(), RoleNames.AGENT)
                || UserManager.IsInRole(User.Identity.GetUserId(), RoleNames.OFFICE_MANAGER);
            if (res)
            {
                return RedirectToAction("Index", CUSTOMER_OPERATIONS_PATH);
            }
            else
            {
                errorModel.ErrorMessage = "Admin cannot access customers resource";
                return View(NOT_AUTHORIZED_PATH, errorModel);
            }

        }

        public ActionResult CreateCustomer()
        {
            var res = UserManager.IsInRole(User.Identity.GetUserId(), RoleNames.AGENT)
                || UserManager.IsInRole(User.Identity.GetUserId(), RoleNames.OFFICE_MANAGER);
            if (res)
            {
                return RedirectToAction("Create", CUSTOMER_OPERATIONS_PATH);
            }
            else
            {
                errorModel.ErrorMessage = "Admin cannot access customers resource";
                return View(NOT_AUTHORIZED_PATH, errorModel);
            }
        }

        public ActionResult GetCustomerDetails(int? id)
        {
            var res = UserManager.IsInRole(User.Identity.GetUserId(), RoleNames.AGENT)
            || UserManager.IsInRole(User.Identity.GetUserId(), RoleNames.OFFICE_MANAGER);
            if (id.HasValue)
            {
                if (res)
                {
                    return RedirectToAction("Details", CUSTOMER_OPERATIONS_PATH, new { id = id });
                }
                else
                {
                    errorModel.ErrorMessage = "Admin cannot access customers resource";
                    return View(NOT_AUTHORIZED_PATH, errorModel);
                }
            }
            return HttpNotFound();
        }

        public ActionResult EditCustomer(int? id)
        {
            if (id.HasValue)
            {
                var res = UserManager.IsInRole(User.Identity.GetUserId(), RoleNames.AGENT)
                || UserManager.IsInRole(User.Identity.GetUserId(), RoleNames.OFFICE_MANAGER);

                if (res)
                {
                    return RedirectToAction("Edit", CUSTOMER_OPERATIONS_PATH, new { id = id });
                }
                else
                {
                    errorModel.ErrorMessage = "Admin cannot access customers resource";
                    return View(NOT_AUTHORIZED_PATH, errorModel);
                }
            }
            return HttpNotFound();
        }
        #endregion

    }
}

asp-final-project-team-alpha-main/Real_Estate_Project/Views/CustomerOperations/Create.cshtml
@model Real_Estate_Project.ViewModels.CustomerViewModel
@using Real_Estate_Project.DataAccess.Data_Models

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="card text-white bg-dark mb-3" style="margin-bottom:2em;">
    <div class="card-body">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <h1 style="text-align:center">Create Customer</h1>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.Partial("_CustomerModifications", Model)
            <br />
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-success" />
                </div>
            </div>

        }
        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

asp-final-project-team-alpha-main/Real_Estate_Project/Views/CustomerOperations/Delete.cshtml
@model Real_Estate_Project.ViewModels.CustomerViewModel

@{
    ViewBag.Title = "Delete";
}


<h2>Delete</h2>

<div class="card">
    <div class="card-body">
        <h3>Are you sure you want to delete this?</h3>
        <h4>Customer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.inputModel.FullName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.inputModel.FullName)
            </dd>

        </dl>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-outline-danger" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</div>

asp-final-project-team-alpha-main/Real_Estate_Project/Views/CustomerOperations/Details.cshtml
@model Real_Estate_Project.ViewModels.CustomerViewModel

@{ ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml"; }

<h2>Details</h2>

<div class="row">
    <div class="col-3">
        <div class="card text-white bg-dark mb-3">

            <img class="card-img-top" src="https://www.flaticon.com/premium-icon/icons/svg/2967/2967324.svg"
                 style="width:5em;height:5em;">

            <div class="card-body">
                <div class="row">
                    <div class="col-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.inputModel.DateCreated, new { @class = "text-primary" })
                            @Html.DisplayFor(model => model.inputModel.DateCreated)
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.inputModel.UserCreator, new { @class = "text-primary" })
                            @Html.DisplayFor(model => model.inputModel.UserCreator.FullName)
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.inputModel.DateUpdated, new { @class = "text-primary" })
                            @Html.DisplayFor(model => model.inputModel.DateUpdated)
                        </div>

                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.inputModel.UserUpdator, new { @class = "text-primary" })
                            @Html.DisplayFor(model => model.inputModel.UserUpdator.FullName)
                        </div>
                    </div>
                </div>
            </div>
            <a class="btn btn-outline-warning" role="button" href="@Url.Action("Edit","CustomerOperations",new {id =  Model.inputModel.ID})">Edit</a>
            <a class="btn btn-outline-danger" role="button" href="@Url.Action("Index","CustomerOperations")">Back to List</a>
        </div>
    </div>

    <div class="col-9">
        <div class="card text-white bg-secondary mb-3">
            <div class="card-body">
                <br />
                <div class="row">
                    <div class="col-6">
                        <div class="card text-white bg-dark mb-3">
                            <div class="card-body">
                                <h5 class="card-title">Basic Information</h5>
                                <div class="row">
                                    <div class="col-4">
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.inputModel.FirstName, new { @class = "text-primary" })
                                            @Html.DisplayFor(model => model.inputModel.FirstName)
                                        </div>
                                    </div>
                                    <div class="col-4">
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.inputModel.MiddleName, new { @class = "text-primary" })
                                            @Html.DisplayFor(model => model.inputModel.MiddleName)
                                        </div>

                                    </div>
                                    <div class="col-4">
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.inputModel.LastName, new { @class = "text-primary" })
                                            @Html.DisplayFor(model => model.inputModel.LastName)
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="card text-white bg-dark mb-3">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-6">
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.inputModel.CustomerAddress.StreetAddress, new { @class = "text-primary" })
                                            @Html.DisplayFor(model => model.inputModel.CustomerAddress.StreetAddress)
                                        </div>
                                    </div>

                                    <div class="col-6">
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.inputModel.CustomerAddress.Municipality, new { @class = "text-primary" })
                                            @Html.DisplayFor(model => model.inputModel.CustomerAddress.Municipality)
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-6">
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.inputModel.CustomerAddress.Province, new { @class = "text-primary" })
                                            @Html.DisplayFor(model => model.inputModel.CustomerAddress.Province)
                                        </div>

                                    </div>
                                    <div class="col-6">
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.inputModel.CustomerAddress.PostalCode, new { @class = "text-primary" })
                                            @Html.DisplayFor(model => model.inputModel.CustomerAddress.PostalCode)
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-6">
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.inputModel.PhoneNumber, new { @class = "text-primary" })
                                            @Html.DisplayFor(model => model.inputModel.PhoneNumber)
                                        </div>
                                    </div>
                                    <div class="col-6">
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.inputModel.dateOfBirth, new { @class = "text-primary" })
                                            @Html.DisplayFor(model => model.inputModel.dateOfBirth)
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

asp-final-project-team-alpha-main/Real_Estate_Project/Views/CustomerOperations/Edit.cshtml
@model Real_Estate_Project.ViewModels.CustomerViewModel
@using Real_Estate_Project.DataAccess.Data_Models
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

<div class="card text-white bg-dark mb-3" style="margin-bottom:2em;">
    <div class="card-body">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <h4>Customer</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.inputModel.ID)
            @Html.HiddenFor(model => model.inputModel.DateCreated)
            @Html.HiddenFor(model => model.inputModel.UserCreatorId)
            @Html.HiddenFor(model => model.inputModel.AddressID)
            @Html.HiddenFor(model => model.inputModel.CustomerAddress.ID)
            @Html.HiddenFor(model => model.inputModel.IsActive)
            @Html.Partial("_CustomerModifications", Model)
            <br />
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-success" />
                </div>
            </div>
        }
        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

asp-final-project-team-alpha-main/Real_Estate_Project/Views/CustomerOperations/Index.cshtml
@model Real_Estate_Project.ViewModels.CustomerViewModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<br />
<div class="row">
    <div class="col-4">
       <div class="jumbotron card border-info mb-3">
           <div class="row">
               <h1 class="display-4" style="margin:0 auto;">Customers</h1>
           </div>
           <br />
           <div class="row">
               <p class="lead" style="margin:0 auto;">Register your customers to unlock the full potential of REAP</p>
           </div>
           <br />
           <hr />
           <div class="row">
               <button class="btn btn-outline-warning" style="margin: 0 auto;">
                   @Html.ActionLink("Register Customer", "CreateCustomer", "RoleFilter")
               </button>
           </div>
     </div>
</div>


<div class="col-6">
    @if (Model.customerList.Count > 0)
    {
        <div style="height:40em;width:70em;overflow:auto;padding-left:1em; padding-right:1em;">
            <div class="card text-white bg-secondary mb-3 ">
                <div class="card-body">
                    <div class="row">
                        @foreach (var item in Model.customerList)
                        {
                             <div class="col-4">
                                 <div class="card text-white bg-dark mb-3  mb-3 card border-success mb-3">
                                     <div class="card-body">
                                         <img class="card-img-top" src="https://www.flaticon.com/premium-icon/icons/svg/2967/2967324.svg"
                                              style="width:20%;height:20%;">
                                         <h5 class="card-title">@item.FullName</h5>
                                         <hr />
                                         <div class="form-group">
                                             @Html.LabelFor(model => model.inputModel.PhoneNumber, new { @class = "text-success" })
                                             @Html.DisplayFor(modelItem => item.PhoneNumber)
                                         </div>

                                         <div class="form-group">
                                             @Html.LabelFor(model => model.inputModel.CustomerAddress.Municipality, new { @class = "text-success" })
                                             @Html.DisplayFor(modelItem => item.CustomerAddress.Municipality)
                                         </div>

                                         <div class="form-group">
                                             @Html.LabelFor(model => model.inputModel.CustomerAddress.PostalCode, new { @class = "text-success" })
                                             @Html.DisplayFor(modelItem => item.CustomerAddress.PostalCode)
                                         </div>

                                         <a href="@Url.Action("EditCustomer", "RoleFilter", new { id = item.ID })">
                                             <i class="fas fa-edit"></i>
                                         </a>
                                         |
                                         <a href="@Url.Action("GetCustomerDetails", "RoleFilter", new { id = item.ID })">
                                             <i class="fas fa-info-circle"></i>
                                         </a>
                                         |
                                         <a href="@Url.Action("Delete", "CustomerOperations", new { id = item.ID })">
                                             <i class="fas fa-trash-alt"></i>
                                         </a>
                                     </div>
                                 </div>
                             </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    }
    else
    {
        <div class="jumbotron card border-danger mb-3">
            <div class="row">
                <p class="lead" style="margin:0 auto;">No Customers Available</p>
            </div>
        </div>
    }

</div>
</div>