asp-final-project-team-alpha-main/Real_Estate_Project/Models/Domain_Models/Viewing_Models/Viewing.cs
using Real_Estate_Project.DataAccess.Data_Models;
using Real_Estate_Project.Models.Listing_Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Real_Estate_Project.Models.Domain_Models.Viewing_Models
{
    public class Viewing
    {
        public Viewing()
        {
            ViewingHost = new OperatingUser();
            Listing = new Listing();
            Customer = new Customer();
        }

        [Key]
        public int ID { get; set; }

        [Required]
        [Display(Name = "Viewing Host")]
        public virtual OperatingUser ViewingHost { get; set; }


        [Display(Name = "Property to View")]
        public virtual Listing Listing { get; set; }

        [Required]
        [Display(Name = "Viewing Guest")]
        public virtual Customer Customer { get; set; }

        [Required]
        [Display(Name = "Starting on")]
        public DateTime StartDate { get; set; }

        [Required]
        [Display(Name ="Ending on")]
        public DateTime EndDate { get; set; }

        [Display(Name = "Created On")]
        public DateTime CreatedDate { get; set; }

        [Display(Name = "Updated On")]
        public DateTime UpdatedDate { get; set; }

        public bool IsActive { get; set; }

        public int? UserCreatorId { get; set; }

        public int? UserUpdatorId { get; set; }

        [ForeignKey("UserCreatorId")]
        public  OperatingUser UserCreator { get; set; }

        [ForeignKey("UserUpdatorId")]
        public  OperatingUser UserUpdator { get; set; }
    }
}

asp-final-project-team-alpha-main/Real_Estate_Project/ViewModels/Viewing_View_Models/ViewingViewModel.cs
using Real_Estate_Project.DataAccess.Data_Models;
using Real_Estate_Project.Models.Domain_Models;
using Real_Estate_Project.Models.Domain_Models.Viewing_Models;
using Real_Estate_Project.Models.Listing_Models;
using Real_Estate_Project.ViewModels.Viewing_View_Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Real_Estate_Project.ViewModels
{
    public class ViewingViewModel
    {
        public ViewingViewModel()
        {
            Listings = new List<Listing>();
            Agents = new List<OperatingUser>();
            Customers = new List<Customer>();
            Viewings = new List<Viewing>();
            DurationList = new List<int>();
            ViewingStart = DateTime.Now;
        }

        [Required]
        [Display(Name="Hosting Agent")]
        public int AgentId { get; set; }
        
        [Required]
        [Display(Name ="Viewing Customer")]
        public int CustomerID { get; set; }

        [Required]
        [Display(Name ="Property")]
        public int ListingId { get; set; }

        public string PickedListingPostalCode { get; set; }

        public int CreatedById { get; set; }

        public int UpdatedById { get; set; }

        [Required]
        [Display(Name ="Viewing Date and Time")]
        [DataType(DataType.DateTime)]
        [DisplayFormat(ApplyFormatInEditMode = true,
        DataFormatString = "{0:MM/dd/yyyy HH:mm}")]
        public DateTime ViewingStart { get; set; }


        [Display(Name ="Duration In minutes")]
        public int ViewingDuration { get; set; }

        public List<int> DurationList { get; set; }

        public ViewingDateFilter ViewingDateFilter { get; set; }

        public List<Viewing> Viewings { get; set; }

        public List<Listing> Listings { get; set; }

        public List<OperatingUser> Agents { get; set; }

        public List<Customer> Customers { get; set; }

        public Viewing ReadonlyViewingModel { get; set; }

    }
}

asp-final-project-team-alpha-main/Real_Estate_Project/Controllers/ViewingsController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Real_Estate_Project.Authorization_Utilities;
using Real_Estate_Project.Business_services.ViewingService;
using Real_Estate_Project.DataAccess.Interfaces;
using Real_Estate_Project.Models.Domain_Models;
using Real_Estate_Project.Models.Domain_Models.Listing_Models;
using Real_Estate_Project.Models.Domain_Models.Viewing_Models;
using Real_Estate_Project.ViewModels;

namespace Real_Estate_Project.Controllers
{
    public class ViewingsController : Controller
    {

        private const string NOT_AUTHORIZED_PATH = "RoleNotAuthorized";
        private SimpleErrorModel errorModel;
        private ViewingViewModel model;
        private IViewingRepo _viewingRepo;
        private IViewingService _viewingService;


        public ViewingsController
            (IViewingRepo viewingRepo,
            IViewingService viewingService,
            ViewingViewModel viewingVM,
            SimpleErrorModel errorM)
        {
            _viewingRepo = viewingRepo;
            _viewingService = viewingService;
            model = viewingVM;
            errorModel = errorM;

        }


        public async Task<ViewingViewModel> GetDefaultViewModelEntry()
        {
            var viewModel = new ViewingViewModel();
            var listings = _viewingService.GetListingsList();
            var customers = _viewingService.GetCustomersList();
            var agents = _viewingService.GetAgentsList();

            await Task.WhenAll(listings, customers, agents);

            viewModel.Listings = listings.Result;
            viewModel.Customers = customers.Result;
            viewModel.Agents = agents.Result;
            viewModel.DurationList = _viewingService.GetDurationSlots();

            return viewModel;
        }


        [Authorize(Roles = RoleNames.OFFICE_MANAGER + "," + RoleNames.ADMIN + "," + RoleNames.AGENT)]
        public async Task<ActionResult> Index()
        {
            try
            {
                var viewings = await _viewingRepo.GetViewingsByDate
                (DateTime.Now, DateTime.Now.AddMonths(3));

                if (viewings != null)
                    model.Viewings = viewings;
            }
            catch(Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }
            return View(model);
        }


        [Authorize(Roles = RoleNames.OFFICE_MANAGER + "," + RoleNames.ADMIN + "," + RoleNames.AGENT)]
        public async Task<ActionResult> GetAllViewings()
        {
            try
            {
                var viewingsList =  await _viewingRepo.GetAll();

                if (viewingsList == null)
                    return HttpNotFound();

                model.Viewings = viewingsList;
            }
            catch (Exception ex)
            {
                ModelState.AddModelError
                (string.Empty, ex.Message);
            }
            return View("Index",model);
        }


        [HttpPost]
        [Authorize(Roles = RoleNames.OFFICE_MANAGER + "," + RoleNames.ADMIN + "," + RoleNames.AGENT)]
        public async Task<ActionResult> GetViewingsByDateRange
         (ViewingViewModel dateFilterInputModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var viewingList =await _viewingRepo.GetViewingsByDate(
                        dateFilterInputModel.ViewingDateFilter.StartingDateRange,
                        dateFilterInputModel.ViewingDateFilter.EndingDateRange);

                    if (viewingList == null)
                        return HttpNotFound();

                    model.Viewings = viewingList;

                }
                catch (Exception ex)
                {
                    ModelState.AddModelError
                    (string.Empty, ex.Message);
                }
                return View("Index", model);
            }
            return RedirectToAction("Index");
        }


        [Authorize(Roles = RoleNames.OFFICE_MANAGER + "," + RoleNames.ADMIN + "," + RoleNames.AGENT)]
        public async Task<ActionResult> Details(int? id)
        {
            if (id.HasValue)
            {
                try
                {
                    var viewingRes = await _viewingRepo.Get(id.Value);

                    if (viewingRes != null)
                    {
                        if (viewingRes.Listing.ImagesContent != null)
                        {
                            var listingImages = new List<ListingImage>
                                (viewingRes.Listing.ImagesContent);

                            viewingRes.Listing.ImagesContent = new List<ListingImage>();

                            listingImages.ForEach(i =>viewingRes.Listing.ImagesContent.Add(i));

                        }

                        model = _viewingService
                            .GetViewingViewModelFromModel(viewingRes);
                    }
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                }
                return View(model);
            }
            return HttpNotFound();
        }


        [Authorize(Roles = RoleNames.OFFICE_MANAGER + "," + RoleNames.ADMIN + "," + RoleNames.AGENT)]
        public async Task<ActionResult> Create(int? listingId)
        {
            try
            {
                var currentLoggedUserId = User.Identity.GetUserId();

                var currentLoggedUserRes = await UserIdentityManager.GetUserById
                                           (currentLoggedUserId);

                if (!currentLoggedUserRes.registeredUser.IsVerified
                    && currentLoggedUserRes.registeredUser.RoleID == RoleNames.AGENT)
                {
                    errorModel.ErrorMessage = 
                        "Agent cannot access viewing resource.\n Agent is not verified";

                    return View(NOT_AUTHORIZED_PATH, errorModel);
                }


                model = await GetDefaultViewModelEntry();

                if (listingId.HasValue)
                {
                    model.ListingId = listingId.Value;

                    var listingInDb = await _viewingRepo.GetListingById(model.ListingId);

                    model.PickedListingPostalCode =
                        $@"{listingInDb.ListingAddress.PostalCode} { listingInDb.ListingAddress.StreetAddress} {listingInDb.ListingAddress.Municipality}";
                }
                else
                {
                    model.PickedListingPostalCode = "No Listing is Picked";
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }
            return View(model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = RoleNames.OFFICE_MANAGER + "," + RoleNames.ADMIN + "," + RoleNames.AGENT)]
        public async Task<ActionResult> Create(ViewingViewModel model)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    if(model.ListingId == 0)
                    {
                        model = await GetDefaultViewModelEntry();

                        model.PickedListingPostalCode = "No Listing is Picked";
                        ModelState.AddModelError(string.Empty, "Please pick a Listing");

                        return View(model);
                    }

                    var modelState = ModelState;
                    var viewingToCreate = new Viewing();
                    viewingToCreate = await _viewingService
                            .GetViewingFromViewModel(model);

                    if (await _viewingService.IsViewingValid
                        (viewingToCreate,ModelState))
                    {
                        var currentLoggedUserId = User.Identity.GetUserId();
                        var currentLoggedUserRes = await UserIdentityManager
                            .GetUserById(currentLoggedUserId);

                        viewingToCreate.CreatedDate = DateTime.Now;
                        viewingToCreate.UpdatedDate = DateTime.Now;

                        viewingToCreate.UserCreatorId = 
                            currentLoggedUserRes.registeredUser.ID;

                        viewingToCreate.UserUpdatorId = 
                            currentLoggedUserRes.registeredUser.ID;

                        viewingToCreate.IsActive = true;

                        var result = await _viewingRepo.Create
                            (viewingToCreate);

                        return RedirectToAction("Index");
                    }
                    else
                    {
                        model = await GetDefaultViewModelEntry();
                        return View(model);
                    }
                }
                catch(Exception ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                }
            }

            return View(model);
        }


        [Authorize(Roles = RoleNames.OFFICE_MANAGER + "," + RoleNames.ADMIN + "," + RoleNames.AGENT)]
        public async Task<ActionResult> Edit(int? listingId,int? id)
        {
            try
            {
                var currentLoggedUserId = User.Identity.GetUserId();

                var currentLoggedUserRes = await UserIdentityManager.GetUserById
                                           (currentLoggedUserId);

                if (!currentLoggedUserRes.registeredUser.IsVerified
                    && currentLoggedUserRes.registeredUser.RoleID == RoleNames.AGENT)
                {
                    errorModel.ErrorMessage =
                     "Agent cannot access viewing resource.\n Agent is not verified";

asp-final-project-team-alpha-main/Real_Estate_Project/Views/Viewings/Details.cshtml
@model Real_Estate_Project.ViewModels.ViewingViewModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>
<div class="row">
    <div class="col-3">
        <div class="card text-white bg-dark mb-3">
            <img class="card-img-top" src="https://www.flaticon.com/premium-icon/icons/svg/3638/3638766.svg"
                 style="width:5em;height:5em;">
            <hr />
            <div class="card-body">
                <div class="row">
                    <div class="col-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.ReadonlyViewingModel.CreatedDate, new { @class = "text-primary" })
                            @Html.DisplayFor(model => model.ReadonlyViewingModel.CreatedDate)
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.ReadonlyViewingModel.UserCreator, new { @class = "text-primary" })
                            @Html.DisplayFor(model => model.ReadonlyViewingModel.UserCreator.FullName)
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.ReadonlyViewingModel.UpdatedDate, new { @class = "text-primary" })
                            @Html.DisplayFor(model => model.ReadonlyViewingModel.UpdatedDate)
                        </div>

                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.ReadonlyViewingModel.UserUpdator, new { @class = "text-primary" })
                            @Html.DisplayFor(model => model.ReadonlyViewingModel.UserUpdator.FullName)
                        </div>
                    </div>
                </div>

            </div>
            <a class="btn btn-outline-warning" role="button" href="@Url.Action("Edit","Viewings",new {id =  Model.ReadonlyViewingModel.ID})">Edit</a>
            <a class="btn btn-outline-danger" role="button" href="@Url.Action("Index","Viewings")">Back to List</a>
        </div>
    </div>


    <div class="col-9" style="margin-bottom:3em">
        <div class="card text-white bg-secondary mb-3">
            <div class="card-body">
                <br />
                <div class="row">
                    <div class="col-6">
                        <div class="card text-white bg-dark mb-3">
                            <div class="card-body">
                                <h5 class="card-title">Basic Information</h5>
                                <div class="row">
                                    <div class="col-3">
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.ReadonlyViewingModel.ViewingHost, new { @class = "text-primary" })
                                            @Html.DisplayFor(model => model.ReadonlyViewingModel.ViewingHost.FullName)
                                        </div>
                                    </div>
                                    <div class="col-3">
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.ReadonlyViewingModel.Customer, new { @class = "text-primary" })
                                            @Html.DisplayFor(model => model.ReadonlyViewingModel.Customer.FullName)
                                        </div>

                                    </div>
                                    <div class="col-3">
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.ReadonlyViewingModel.StartDate, new { @class = "text-primary" })
                                            @Html.DisplayFor(model => model.ReadonlyViewingModel.StartDate)
                                        </div>
                                    </div>
                                    <div class="col-3">
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.ReadonlyViewingModel.EndDate, new { @class = "text-primary" })
                                            @Html.DisplayFor(model => model.ReadonlyViewingModel.EndDate)
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="card text-white bg-dark mb-3">
                              <div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
                                @if (Model.ReadonlyViewingModel.Listing.ImagesContent.Count > 0)
                                {
                                    <div class="carousel-inner">
                                        @for (int i = 0; i < Model.ReadonlyViewingModel.Listing.ImagesContent.Count; i++)
                                        {
                                            if (i == 0)
                                            {
                                                <div class="carousel-item active">
                                                    <img src="@Url.Action("DisplayFullImage","ListingOperations" ,
                                                             new { id = Model.ReadonlyViewingModel.Listing.ImagesContent.ToArray()[i].ID })"
                                                         alt="Listing Image" class="d-block w-100" />
                                                </div>
                                            }
                                            else
                                            {
                                                <div class="carousel-item">
                                                    <img src="@Url.Action("DisplayFullImage","ListingOperations", 
                                                             new { id = Model.ReadonlyViewingModel.Listing.ImagesContent.ToArray()[i].ID })"
                                                         alt="Listing Image" class="d-block w-100" />
                                                </div>
                                            }
                                        }

                                    </div>
                                }
                                <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
                                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                    <span class="sr-only">Previous</span>
                                </a>
                                <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
                                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                    <span class="sr-only">Next</span>
                                </a>
                            </div>
                            <div class="card-body">
                                <h5 class="card-title">Property Information</h5>
                                <div class="row">
                                    <div class="col-6">
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.ReadonlyViewingModel.Listing, new { @class = "text-primary " })
                                            @Html.DisplayFor(model => model.ReadonlyViewingModel.Listing.ListingAddress.PostalCode)
                                        </div>

                                    </div>
                                    <div class="col-6">
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.ReadonlyViewingModel.Listing.SquareFootage, new { @class = "text-primary" })
                                            @Html.DisplayFor(model => model.ReadonlyViewingModel.Listing.SquareFootage)
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-6">
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.ReadonlyViewingModel.Listing.CityArea, new { @class = "text-primary" })
                                            @Html.DisplayFor(model => model.ReadonlyViewingModel.Listing.CityArea)
                                        </div>
                                    </div>
                                    <div class="col-6">
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.ReadonlyViewingModel.Listing.Price, new { @class = "text-primary" })
                                            @Html.DisplayFor(model => model.ReadonlyViewingModel.Listing.Price)
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    </div>
            </div>
        </div>
    </div>
</div>

asp-final-project-team-alpha-main/Real_Estate_Project/Views/Viewings/Index.cshtml
@model Real_Estate_Project.ViewModels.ViewingViewModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<br />

<div class="row">
    <div class="col-4">
        <div class="jumbotron card border-info mb-3">
            <h1 style="text-align:center">Viewings</h1>
            <hr />
            <div class="row">
                <div class="card text-white bg-dark mb-3" style=" margin:0 auto">
                    <div class="card-body">
                        <h5 class="card-title" style="text-align:center">Filter By Date</h5><hr />
                        <div class="col-12">
                            @using (Html.BeginForm("GetViewingsByDateRange", "Viewings", FormMethod.Post))
                            {
                                <div class="row">
                                    <div class="col-6">
                                        @Html.LabelFor(model => model.ViewingDateFilter.StartingDateRange, htmlAttributes: new { @class = "control-label col-6" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.ViewingDateFilter.StartingDateRange, new { htmlAttributes = new { @class = "form-control", type = "Date" } })
                                            @Html.ValidationMessageFor(model => model.ViewingDateFilter.StartingDateRange, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <div class="col-6">
                                        @Html.LabelFor(model => model.ViewingDateFilter.EndingDateRange, htmlAttributes: new { @class = "control-label col-6" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.ViewingDateFilter.EndingDateRange, new { htmlAttributes = new { @class = "form-control", type = "Date" } })
                                            @Html.ValidationMessageFor(model => model.ViewingDateFilter.EndingDateRange, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                                <br />
                                <div class="col-4">
                                    <div class="col-md-10">
                                        <input type="submit" value="See Available Viewings" class="btn btn-outline-info" />
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>

                <div class="row" style="margin: 0 auto;">

                    <button class="btn btn-outline-warning" style="margin-right: 50px; margin-top:20px;">
                        @Html.ActionLink("Create New", "Create")
                    </button>

                    <button class="btn btn-outline-danger" style="margin-left: 50px; margin-top:20px;">
                        @Html.ActionLink("See all Viewings", "GetAllViewings")
                    </button>


                </div>
            </div>
        </div>
    </div>

    <div class="col-6">
        @if (Model.Viewings.Count > 0)
        {
            <div style="height:40em;width:70em;overflow:auto;padding-left:1em; padding-right:1em;">
                <div class="card text-white bg-secondary mb-3 ">
                    <div class="card-body">
                        <div class="row">
                            @foreach (var item in Model.Viewings)
                            {
                            <div class="col-4" style="margin-bottom:3em">
                                <div class="card text-white bg-dark mb-3 card border-success mb-3">
                                    <div class="card-body">
                                        <img class="card-img-top" src="https://www.flaticon.com/premium-icon/icons/svg/3638/3638766.svg"
                                             style="width:20%;height:20%;">
                                        <h5 class="card-title"></h5>
                                        <hr />
                                        <div class="form-group">
                                            @Html.LabelFor(model => item.Customer, new { @class = "text-success" })
                                            @Html.DisplayFor(modelItem => item.Customer.FullName)
                                        </div>

                                        <div class="form-group">
                                            @Html.LabelFor(model => item.ViewingHost, new { @class = "text-success" })
                                            @Html.DisplayFor(modelItem => item.ViewingHost.FullName)
                                        </div>

                                        <div class="form-group">
                                            @Html.LabelFor(model => item.Listing, new { @class = "text-success" })
                                            @Html.DisplayFor(modelItem => item.Listing.ListingAddress.PostalCode)
                                        </div>

                                        <div class="form-group">
                                            @Html.LabelFor(model => item.StartDate, new { @class = "text-success" })
                                            @Html.DisplayFor(modelItem => item.StartDate)
                                        </div>

                                        <a href="@Url.Action("Edit", "Viewings", new { id = item.ID })">
                                            <i class="fas fa-edit"></i>
                                        </a>
                                        |
                                        <a href="@Url.Action("Details", "Viewings", new { id = item.ID })">
                                            <i class="fas fa-info-circle"></i>
                                        </a>
                                        |
                                        <a href="@Url.Action("Delete", "Viewings", new { id = item.ID })">
                                            <i class="fas fa-trash-alt"></i>
                                        </a>
                                    </div>
                                </div>
                            </div>
                            }
                        </div>
                    </div>
                </div>

            </div>
        }
        else
        {
            <div class="jumbotron card border-danger mb-3">
                <div class="row">
                    <p class="lead" style="margin:0 auto;">No Viewings Available</p>
                </div>
            </div>
        }
    </div>
</div>