asp-final-project-team-alpha-main/Real_Estate_Project/ViewModels/Listing_ViewModels/SearchListingViewModel.cs
using PagedList;
using Real_Estate_Project.Models.Listing_Models;
using Real_Estate_Project.ViewModels.Listing_ViewModels;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using System.Web.UI;

namespace Real_Estate_Project.ViewModels
{
    public class SearchListingViewModel
    {
        public SearchListingViewModel()
        {
            SearchModel = new SearchBoxViewModel();
        }


        //Only for When Editing
        public int? ViewingID { get; set; }

        public IPagedList<Listing> Listings { get; set; }

        public Listing DisplayOnlyModel { get; set; }


        //Order by Params
        public string PostalCodeParam { get; set; }

        public string PriceParam { get; set; }

        public string SquareFootageParam { get; set; }

        public string NumOfBedsParam { get; set; }

        public string NumOfBathsParam { get; set; }

        public string NumOfStoriesParam { get; set; }

        public string CurrentSort { get; set; }

        //Searching Params
        public string CurrentMunicipalitySearch { get; set; }

        [Display(Name ="Filter By Heating Type")]
        public List<SelectListItem> heatingTypesSearch { get; set; }


        [Display(Name ="Filter By Feature")]
        public List<SelectListItem> propertyFeaturesSearch { get; set; }

        public SearchBoxViewModel SearchModel { get; set; }

        public Dictionary<string, Pair> PriceRangeList { get; set; }
    }
}

asp-final-project-team-alpha-main/Real_Estate_Project/Controllers/ListingOperationsController.cs
using Microsoft.AspNet.Identity;
using PagedList;
using PagedList.EntityFramework;
using Real_Estate_Project.Authorization_Utilities;
using Real_Estate_Project.DataAccess.Interfaces;
using Real_Estate_Project.Models.Listing_Models;
using Real_Estate_Project.View_Uitlity_Model_Helpers;
using Real_Estate_Project.ViewModels;
using Real_Estate_Project.ViewModels.Listing_ViewModels;
using System;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Real_Estate_Project.Controllers
{

    public class ListingOperationsController : Controller
    {
        private static string DEFAULT_IMAGE = 
            "https://www.flaticon.com/premium-icon/icons/svg/2243/2243783.svg";

        private ICustomerRepo _customerRepo;
        private IOperatingUserRepo _userRepo;
        private IListingRepo _listingRepo;
        private IListingImageHelper _imageHelper;
        private ListingViewModel model;

        public ListingOperationsController
            (IOperatingUserRepo userRepo, ICustomerRepo customerRepo
            , IListingRepo listingRepo, ListingViewModel listingVM, IListingImageHelper imageHelper)
        {
            _userRepo = userRepo;
            _customerRepo = customerRepo;
            _listingRepo = listingRepo;
            model = listingVM;
            _imageHelper = imageHelper;
        }


        public async Task<ActionResult> DisplayFile(int id)
        {
            try
            { 
                var imageToDisplay = await _listingRepo.GetListingThumbnail(id);

                if (imageToDisplay == null)
                    return Content(DEFAULT_IMAGE);


                return File(imageToDisplay.ThumbnailContent, imageToDisplay.ContentType);
            }
            catch (Exception ex)
            {

                ModelState.AddModelError(string.Empty, ex.Message);
                return File(new byte[0],string.Empty);
            }

        }

        public async Task<ActionResult> DisplayFullImage(int id)
        {
            try
            {
                var imageToDisplay = await _listingRepo.GetListingImage(id);

                if (imageToDisplay == null)
                    return File(new byte[0], string.Empty);


                return File(imageToDisplay.Content,
                    imageToDisplay.ContentType);
            }
            catch (Exception ex)
            {

                ModelState.AddModelError(string.Empty, ex.Message);
                return File(new byte[0], string.Empty);
            }
        }

        public async Task<ListingViewModel> GetDefaultViewModelEntry()
        {
            var viewModel = new ListingViewModel();

            var heatingDbList = _listingRepo.GetAllHeating();
            var propFeaturesDbList = _listingRepo.GetAllFeatures();
            var customersDbList = _customerRepo.GetAll();
            var agentsDbList = _userRepo.GetAllByRole(RoleNames.AGENT);


            await Task.WhenAll(heatingDbList, propFeaturesDbList,
                                customersDbList, agentsDbList);


            viewModel.HeatingListToSelect = ListingViewHelperUtilites.
            GetHeatingTypesToListItems(heatingDbList.Result);

            viewModel.FeaturesListToSelect = ListingViewHelperUtilites.
            GetPropertyFeaturesToListItems(propFeaturesDbList.Result);

            viewModel.Agents = agentsDbList.Result;

            viewModel.Customers = customersDbList.Result;

            return viewModel;
        }


        [Authorize(Roles = RoleNames.OFFICE_MANAGER + "," + RoleNames.ADMIN + "," + RoleNames.AGENT)]
        public async Task<ActionResult> Index(int page =1)
        {
            try
            {
                var listings = _listingRepo.GetIqueryableListings();

                if (listings != null)
                    model.Listings = await listings.ToPagedListAsync(page,8);

            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }
            return View(model);
        }


        [Authorize(Roles = RoleNames.OFFICE_MANAGER + "," + RoleNames.ADMIN + "," + RoleNames.AGENT)]
        public async Task<ActionResult> Details(int? id)
        {
            if (id.HasValue)
            {
                try
                {
                    var listing = await _listingRepo.Get(id.Value);

                    if (listing == null)
                        return HttpNotFound();

                    model.InputModel = listing;
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                }
                return View(model);
            }
            else
            {
                return HttpNotFound();
            }
        }


        [Authorize(Roles = RoleNames.OFFICE_MANAGER + "," + RoleNames.ADMIN + "," + RoleNames.AGENT)]
        public async Task<ActionResult> Create()
        {
            try
            {
                model = await GetDefaultViewModelEntry();
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }

            return View(model);
        }


        [Authorize(Roles = RoleNames.OFFICE_MANAGER + "," + RoleNames.ADMIN + "," + RoleNames.AGENT)]
        [HttpPost]
        public async Task<ActionResult> Create(ListingViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var modelToInsert = model.InputModel;

                    var currentLoggedUserId = User.Identity.GetUserId();
                    var currentLoggedUserRes = await UserIdentityManager.GetUserById(currentLoggedUserId);

                    modelToInsert = ListingViewHelperUtilites
                        .MapHeatingAndFeaturesToListingModel(model);


                    modelToInsert.DateCreated = DateTime.Now;
                    modelToInsert.DateUpdated = DateTime.Now;
                    modelToInsert.UserCreatorId = currentLoggedUserRes.registeredUser.ID;
                    modelToInsert.UserUpdatorId = currentLoggedUserRes.registeredUser.ID;
                    modelToInsert.IsActive = true;

                    
                    if(!_imageHelper.IsPostedFilesListEmpty(model.ListingImageFiles))
                    {
                        if (_imageHelper.HasImageListExceededSizeLimit(model.ListingImageFiles))
                        {
                            ModelState.AddModelError
                                (string.Empty,
                                "File upload limit exceeded (more than 7 files)");

                            model = await GetDefaultViewModelEntry();
                            model.InputModel = modelToInsert;

                            return View(model);
                        }

                        if (_imageHelper.isValidFileUpload(model.ListingImageFiles))
                        {
                            var imagesList = model.ListingImageFiles;
                            _imageHelper.SetModelImages
                                (modelToInsert, imagesList);
                        }
                        else
                        {
                            ModelState.AddModelError
                                (string.Empty,
                                "One or more File uploads was not valid");

                            model = await GetDefaultViewModelEntry();
                            model.InputModel = modelToInsert;

                            return View(model);

                        }
                    }

                    int res = await _listingRepo.Create(modelToInsert);

                    return RedirectToAction("Details",new { id = modelToInsert.ID});
                }
                else
                {
                    var tmpModel = model.InputModel;
                    model = await GetDefaultViewModelEntry();
                    model.InputModel = tmpModel;

                    return View(model);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                model = await GetDefaultViewModelEntry();

                return View(model);
            }
        }


        [Authorize(Roles = RoleNames.OFFICE_MANAGER + "," + RoleNames.ADMIN + "," + RoleNames.AGENT)]
        public async Task<ActionResult> Edit(int? id)
        {
            try
            {
                if (id.HasValue)
                {
                    var listingRes = await _listingRepo.Get(id.Value);

                    if (listingRes != null)
                    {
                        model = await GetDefaultViewModelEntry();

                        model.ExistingListingImages = 
                            ListingViewHelperUtilites.SetImagesToListItems
                            (listingRes.ImagesContent.ToList());


                        model.FeaturesListToSelect
                            .SetFeaturesTypesToListItems(listingRes.Features);

                        model.HeatingListToSelect
                            .SetHeatingTypesToListItems(listingRes.Heating);

                        model.InputModel = listingRes;

                        return View(model);
                    }
                    else
                    {
                        return HttpNotFound();
                    }
                }
                else
                {
                    return HttpNotFound();
                }

            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View(model);
            }
        }


        [Authorize(Roles = RoleNames.OFFICE_MANAGER + "," + RoleNames.ADMIN + "," + RoleNames.AGENT)]

asp-final-project-team-alpha-main/Real_Estate_Project/Views/ListingOperations/Create.cshtml
@model Real_Estate_Project.ViewModels.ListingViewModel
@using Real_Estate_Project.DataAccess.Data_Models
@using Real_Estate_Project.Models


@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="card text-white bg-dark mb-3" style="margin-bottom:2em;">
    <div class="card-body">

        @using (Html.BeginForm("Create", "ListingOperations", FormMethod.Post, new { enctype = "multipart/form-data",@id ="SubmitForm" }))
        {
            @Html.AntiForgeryToken()
        <h1 style="text-align:center">Create Listing</h1>
        <div class="form-horizontal">

            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.Partial("_ListingModification", Model)

            <div class="form-group">
                @Html.LabelFor(model => model.ListingImageFiles, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.ListingImageFiles, "", new { @type = "file", @multiple = "multiple" })
                    @Html.ValidationMessageFor(model => model.ListingImageFiles, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-outline-success" />
                </div>
            </div>
        </div>
        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}


<script>
    
</script>

asp-final-project-team-alpha-main/Real_Estate_Project/Views/ListingOperations/Details.cshtml
@model Real_Estate_Project.ViewModels.ListingViewModel

@{ ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<h2>Details</h2>
<div class="row">
    <div class="col-5">
        <div class="card text-white bg-dark mb-3">
            <div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
                @if (Model.InputModel.ImagesContent.Count > 0)
                {
                    <div class="carousel-inner">
                        @for (int i = 0; i < Model.InputModel.ImagesContent.Count; i++)
                        {
                            if (i == 0)
                            {
                                <div class="carousel-item active">
                                    <img src="@Url.Action("DisplayFullImage", new { id = Model.InputModel.ImagesContent.ToArray()[i].ID })"
                                         alt="Listing Image" style="height:300px; width:600px;" />
                                </div>
                            }
                            else
                            {
                                <div class="carousel-item">
                                    <img src="@Url.Action("DisplayFullImage", new { id = Model.InputModel.ImagesContent.ToArray()[i].ID })"
                                         alt="Listing Image" style="height:300px; width:600px;" />
                                </div>
                            }
                        }

                    </div>
                }
                <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
            <a class="btn btn-outline-warning" role="button" href="@Url.Action("Edit","ListingOperations",new {id =  Model.InputModel.ID})">Edit</a>
            <a class="btn btn-outline-danger" role="button" href="@Url.Action("Index","ListingOperations")">Back to List</a>
            <a class="btn btn-outline-info" role="button" href="@Url.Action("Create","Viewings",new {listingId = Model.InputModel.ID})">Request Viewing</a>
        </div>
        <div class="row">
            <div class="col-6">
                <iframe width="710"
                        height="550"
                        style="border:0"
                        loading="lazy"
                        allowfullscreen
                        src="https://www.google.com/maps/embed/v1/place?key=AIzaSyCPSyNxsQaSMNRBLaymaNm57vFrW0MQ674
                    &q=@Model.InputModel.ListingAddress.PostalCode , Canada">
                </iframe>
            </div>
        </div>
    </div>
    <div class="col-7">
        <div class="card text-white bg-secondary mb-3">
            <div class="card-body">
                <div class="card text-white bg-dark mb-3">
                    <div class="card-body">
                        <h5 class="card-title">Basic Information</h5>
                        <hr />
                        <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                    <i class="fas fa-user-tag"></i>
                                    @Html.DisplayFor(model => model.InputModel.Customer.FullName)
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                    <i class="fas fa-tags"></i>
                                    @Html.DisplayFor(model => model.InputModel.Price)
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                    <i class="fas fa-user-tie"></i>
                                    @Html.DisplayFor(model => model.InputModel.AssociatedAgent.FullName)
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                    <i class="fas fa-map-marker-alt"></i>
                                    @Html.DisplayFor(model => model.InputModel.ListingAddress.StreetAddress)
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                    <i class="fas fa-city"></i>
                                    @Html.DisplayFor(model => model.InputModel.ListingAddress.Municipality)
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                    <i class="fas fa-map-pin"></i>
                                    @Html.DisplayFor(model => model.InputModel.ListingAddress.Province)
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                    <i class="fab fa-usps"></i>
                                    @Html.DisplayFor(model => model.InputModel.ListingAddress.PostalCode)
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.InputModel.ListingAddress.AddressDetails, 
                                   new { @class = "text-primary" })
                                    @Html.DisplayFor(model => model.InputModel.ListingAddress.AddressDetails)
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                    <i class="fas fa-ruler-combined"></i>
                                    @Html.DisplayFor(model => model.InputModel.SquareFootage)
                                </div>

                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                    <i class="fas fa-bed"></i>
                                    @Html.DisplayFor(model => model.InputModel.NumOfBeds)
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                    <i class="fas fa-bath"></i>
                                    @Html.DisplayFor(model => model.InputModel.NumOfBaths)
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                    <i class="far fa-compass"></i>
                                    @Html.DisplayFor(model => model.InputModel.CityArea)
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-12">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.InputModel.SummaryFeature, new { @class = "text-primary" })
                                    @Html.DisplayFor(model => model.InputModel.SummaryFeature)
                                </div>
                            </div>
                        </div>
                        <hr />
                        <div class="row">
                            <div class="col-6">
                                <ul class="list-group">
                                    <i class="fas fa-fire list-group-item active"></i>
                                    @foreach (var item in Model.InputModel.Heating)
                                    {
                                        <li class="list-group-item text-dark">@item.HeatingType</li>
                                    }
                                </ul>
                            </div>
                            <div class="col-6">
                                <ul class="list-group">
                                    <i class="fas fa-puzzle-piece list-group-item active"></i>
                                    @foreach (var item in Model.InputModel.Features)
                                    {
                                        <li class="list-group-item text-dark">@item.FeatureName</li>
                                    }
                                </ul>
                            </div>
                        </div>
                        <br />
                        <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.InputModel.DateCreated, new { @class = "text-primary" })
                                    @Html.DisplayFor(model => model.InputModel.DateCreated)
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.InputModel.UserCreator, new { @class = "text-primary" })
                                    @Html.DisplayFor(model => model.InputModel.UserCreator.FullName)
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.InputModel.DateUpdated, new { @class = "text-primary" })
                                    @Html.DisplayFor(model => model.InputModel.DateUpdated)
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.InputModel.UserUpdator, new { @class = "text-primary" })
                                    @Html.DisplayFor(model => model.InputModel.UserUpdator.FullName)
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

asp-final-project-team-alpha-main/Real_Estate_Project/Views/ListingOperations/Edit.cshtml
@model Real_Estate_Project.ViewModels.ListingViewModel
@using Real_Estate_Project.DataAccess.Data_Models
@using Real_Estate_Project.Models

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>
<div class="card text-white bg-dark mb-3" style="margin-bottom:2em;">
    <div class="card-body">
        @using (Html.BeginForm("Edit", "ListingOperations",
            FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(model => model.InputModel.ID)
            @Html.HiddenFor(model => model.InputModel.DateCreated)
            @Html.HiddenFor(model => model.InputModel.UserCreatorId)
            @Html.HiddenFor(model => model.InputModel.ListingAddress.ID)
            @Html.HiddenFor(model => model.InputModel.ListingAddressID)
            @Html.HiddenFor(model => model.InputModel.IsActive)

        <div class="form-horizontal">
            <h4>Listing</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="row">
                <div class="col-4">
                    <div class="card text-white bg-secondary mb-3">
                        <div class="card-body">
                            @if (Model.ExistingListingImages.Count > 0)
                            {
                                    <div class="card-group">
                                        @for (int i = 0; i < Model.ExistingListingImages.Count; i++)
                                        {
                                            <div class="col-6">
                                                <br />
                                                <div class="card text-white bg-dark mb-3">
                                                    <div class="card-body">
                                                        <div class="card-title">
                                                            <img src="@Url.Action("DisplayFullImage", new { id= Model.ExistingListingImages[i].Value})"
                                                                 alt="Listing Image" style="width: 50%;" />
                                                        </div>
                                                        @Html.CheckBoxFor(m => m.ExistingListingImages[i].Selected)
                                                        @Html.Label("Check to remove")

                                                        <br />

                                                        @Html.ActionLink("Set as Default Image", "SetDefaultImage", "ListingOperations"
                                                        , new{imageId = Model.ExistingListingImages[i].Value,
                                                        listingId = Model.InputModel.ID}, new { @class = "text-info" })

                                                        @Html.HiddenFor(m => m.ExistingListingImages[i].Value)
                                                        @Html.HiddenFor(m => m.ExistingListingImages[i].Text)
                                                    </div>

                                                </div>
                                            </div>
                                         }
                                    </div>
                            }
                            <div class="form-group">
                                @Html.LabelFor(model => model.ListingImageFiles, htmlAttributes: new { @class = "control-label col-md-12" })
                                <div class="col-md-10">
                                    @Html.TextBoxFor(model => model.ListingImageFiles, "", new { @type = "file", @multiple = "multiple" })
                                    @Html.ValidationMessageFor(model => model.ListingImageFiles, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-8">
                    @Html.Partial("_ListingModification", Model)
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Save" class="btn btn-outline-success" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
        }
        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}